name: dr_lab_lims
description: "Dr Lab LIMS - Laboratory Information Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage for tokens and settings
  shared_preferences: ^2.2.2
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # UI enhancements
  flutter_animate: ^4.5.0
  
  # Platform-specific UI
  fluent_ui: ^4.8.6  # Windows-style UI
  macos_ui: ^2.0.2   # macOS-style UI
  
  # Navigation
  go_router: ^13.2.0
  
  # Responsive design
  flutter_screenutil: ^5.9.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env